### PR TITLE
EVP: Check that key methods aren't foreign when exporting

### LINKED ISSUE #9915: dsa signature failure with external keys / master 2019-09-16
Issue is from e_nss (engine) regression tests - with current(2019-09-16) master "sign-dsa-dss1.test" fail.
Output file sign-dsa-sha1.out after (4) shows:
```
=== sign ===
engine "e_nss" set.
Error Signing Data
00:A7:5E:3F:7B:7F:00:00:error:80000085:E_NSS::Missing private key:/work/src/MyProjects/e_nss/anon-access/origin-local/engines/e_nss_dsa.c:42:
=== verify ===
Error reading signature file cfg-nss-dsa-sha1.sign
```

Commit history:
(4) Add support for verify/verify_recover functions to EVP_SIGNATURE:
commit 390acbebfa90500c79c5014e6659eacda861550c
(3) Implement DSA in the default provider:
commit 4889dadcb8511176c30888c748f1981adc38451d
(2) Add the ability to perform signatures in a provider
commit dfcb5d29b525f5d2b6bd80602dca5efe5fca77bb
(1) DH_check_pub_key_ex was accidentally calling DH_check, so results were undefined.
commit 2b95e8efcf8b99892106070d9ac745a0a369f503

(1) is lest know **good** version , (4) is **broken** version. With (2) or (3) as usually in "group" commits build fail.

### LINKED ISSUE #11179: Current master breaks libp11 RSA signature
MacOS Catalina 10.15.3, Xcode-11.3.1, installed OpenSSL-1.1.1d (reference) and (in a separate dir tree) OpenSSL-3.0 master.

Using `libp11` to perform RSA signature using hardware token accessible via PKCS#11. Fails with both a real hardware token, and SoftHSMv2.

With OpenSSL-1.1.1d (succeeds):
```
$ pkcs11-rsa-pss-sign-demo2
Generating ephemeral file /tmp/derive.89314.text to test RSA-PSS signature...

openssl rand -hex -out /tmp/derive.89314.text 5120

Signing file /tmp/derive.89314.text...
openssl dgst -engine pkcs11 -keyform engine -sign "pkcs11:manufacturer=piv_II;object=SIGN%20key;type=private" -sha384 -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:-1 -out /tmp/derive.89314.text.sig /tmp/derive.89314.text
engine "pkcs11" set.
Enter PKCS#11 token PIN for xxxxxxxxx:
Signature is stored in /tmp/derive.89314.text.sig

Verifying signature:
openssl dgst -engine pkcs11 -keyform engine -sha384 -verify "pkcs11:manufacturer=piv_II;object=SIGN%20pubkey;type=public" -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:-1 -signature /tmp/derive.89314.text.sig  /tmp/derive.89314.text
engine "pkcs11" set.
Verified OK

$
```

With OpenSSL-3.0 (current master, fails):
```
$ pkcs11-rsa-pss-sign-demo3
Generating ephemeral file /tmp/derive.89324.text to test RSA-PSS signature...

openssl3 rand -hex -out /tmp/derive.89324.text 5120

Signing file /tmp/derive.89324.text...
openssl3 dgst -engine pkcs11 -keyform engine -sign "pkcs11:manufacturer=piv_II;object=SIGN%20key;type=private" -sha384 -sigopt rsa_padding_mode:pss -sigopt rsa_pss_saltlen:-1 -out /tmp/derive.89324.text.sig /tmp/derive.89324.text
engine "pkcs11" set.
Enter PKCS#11 token PIN for xxxxxxxxx:
Error Signing Data
C0:2D:B6:09:01:00:00:00:error:rsa routines:rsa_ossl_private_encrypt:missing private key:crypto/rsa/rsa_ossl.c:333:
C0:2D:B6:09:01:00:00:00:error:Provider routines:rsa_sign:RSA lib:providers/implementations/signature/rsa.c:410:

```

Also, see this `libp11` issue for details of a failure trying to sign using SoftHSMv2: https://github.com/OpenSC/libp11/issues/331

### PR DESCRIPTION
**Pull request by levitte**
The EVP_PKEY_ASN1_METHOD function export_to() must check that the key
we're trying to export has a known libcrypto method, i.e. is a built
in RSA_METHOD, DSA_METHOD, etc.  Otherwise, the method may be defined
by the calling application, by an engine, by another library, and we
simply cannot know all the quirks hidden behind that method, if we
have access to the key data, or much anything.

Such keys are simply deemed impossible to export to provider keys,
i.e. have export_to() return 0.  This cascades back to functions like
evp_pkey_export_to_provider() and evp_pkey_upgrade_to_provider() and
their callers.  In most cases, this is fine, but if these get mixed in
with provider side keys in any function, that function will fail.

Fixes #11179
Fixes #9915

### CODE REVIEW

**Comment by levitte** [comment]
While discussing on #11179, I found that this PR was incomplete.  I've just added a commit that completes it.

**Comment by levitte** [comment]
> travis errors

D'oh.  Seems like I mixed up EVP_PKEY_CTX with EVP_PKEY...
Fixed by going back one commit.

**Comment by levitte** [comment]
Travis error is an irrelevant timeout.  CIs are otherwise happy

**Comment by levitte** [comment]
That being said, though, libp11 isn't happy,  The check is done at the wrong level, so this goes back to WIP for a bit

**Comment by levitte** [comment]
Changes pushed, and tested as far as I have been able.  Now, it's up to @mouse07410 and @mtrojnar to try it out with libp11

**Comment by mouse07410** [comment]
Please move the lines you're adding to that function to after this line https://github.com/openssl/openssl/blob/97ace6c2dae451ce8e3b099cf242968ecff128af/crypto/ec/ec_ameth.c#L638

Then all is good.

**Comment by levitte** [comment]
> Please move the lines you're adding to that function to after this line 

Thanks.  Done

File: crypto/ec/ec_ameth.c [hunk 1]
```diff
@@ -637,6 +637,13 @@ int ec_pkey_export_to(const EVP_PKEY *from, void *to_keydata,
             || (ecg = EC_KEY_get0_group(eckey)) == NULL)
         return 0;
 
+    /*
+     * If the DH method is foreign, then we can't be sure of anything, and
```
Comment (slontis) [inline crypto/ec/ec_ameth.c]: update comment to EC

File: crypto/evp/p_lib.c [hunk 2]
```diff
@@ -30,6 +30,7 @@
 #include <openssl/serializer.h>
 #include <openssl/core_names.h>
 
+#include "crypto/dh.h"
```
Comment (slontis) [inline crypto/evp/p_lib.c]: Why?

File: crypto/rsa/rsa_ameth.c [hunk 3]
```diff
@@ -1092,6 +1092,13 @@ static int rsa_pkey_export_to(const EVP_PKEY *from, void *to_keydata,
     OSSL_PARAM *params = NULL;
     int rv = 0;
 
+    /*
+     * If the DH method is foreign, then we can't be sure of anything, and
```
Comment (slontis) [inline crypto/rsa/rsa_ameth.c]: same here

File: crypto/evp/p_lib.c (hunk 2 above)
Comment (levitte) [reply crypto/evp/p_lib.c]: Ah, it's a remnant from earlier incarnations of this PR, where the logic for checking the low level key method was done in this file, i.e. `dh_get_method()` was used.  Will remove,

File: crypto/ec/ec_ameth.c (hunk 1 above)
Comment (levitte) [reply crypto/ec/ec_ameth.c]: Done

File: crypto/rsa/rsa_ameth.c (hunk 3 above)
Comment (levitte) [reply crypto/rsa/rsa_ameth.c]: Fixed

File: crypto/evp/pmeth_fn.c [hunk 4]
```diff
@@ -38,7 +38,7 @@ static int evp_pkey_asym_cipher_init(EVP_PKEY_CTX *ctx, int operation)
      */
     ERR_set_mark();
 
-    if (ctx->engine != NULL)
+    if (ctx->keytype != NULL)
```
Comment (mouse07410) [inline crypto/evp/pmeth_fn.c]: ~~You **sure** about this?~~

Please revert this change. Everything else looks good, and with this one reverted all the OpenSSL and all the relevant `libp11` tests pass.

Comment (levitte) [reply crypto/evp/pmeth_fn.c]: Specifically this one, *only* checking 'ctx->engine`, was plain wrong.

**Comment by levitte** [comment]
Uhmm, the change that removes the check of `ctx->engine` should be handled by the checks in `export_to`, since an engine provided low level method is different than the libcrypto default, i.e. `export_to` should return zero, and the code that tries to export to providers should jump to legacy code.

File: crypto/evp/pmeth_fn.c (hunk 4 above)
Comment (levitte) [reply crypto/evp/pmeth_fn.c]: D'oh!  `!=` should be `==`...

**Comment by mouse07410** [comment]
**Not good**. Without that `|| ctx->engine != NULL`  check several OpenSSL tests keep failing.

**Comment by levitte** [comment]
> check several OpenSSL tests keep failing.

Which ones?  I see pkcs11-uri-without-token.softhsm and search-all-matching-tokens.softhsm failing, do you see something different?

**Comment by mouse07410** [comment]
> Which ones? I see pkcs11-uri-without-token.softhsm and search-all-matching-tokens.softhsm failing, do you see something different?

Yes! OpenSSL's own tests are failing. Within `libp11` - your observation is correct, but I don't start testing it until "make test" completes in the OpenSSL directory.

That's why I think that the check the the engine must be added regardless - with it all the OpenSSL tests pass, **and** all the relevant `libp11` tests too. Those last two tests - I don't know. In theory, any operation on the token should involve cleanup in the end, so should trigger that crash. In practice - as you could see,  all the other tests pass and finish/exit normally. Since real tokens also seem to work correctly, it's probably ok.

**Comment by levitte** [comment]
Ah, now I see what you mean.  Ok, will have a look at what happens when I'm done with some other stuff.

**Comment by slontis** [comment]
Have you forgotten the fips sponsors meeting??

**Comment by mouse07410** [comment]
@levitte may I suggest adding that check for now, add it fixes the OpenSSL tests and unbreaks libp11?

We can figure out later why what you thought should do that check earlier either failed or is not sufficient.

@slontis which one of us? :-) As I too have this week full of meetings. ;-)

**Comment by slontis** [comment]
> @slontis which one of us? :-) As I too have this week full of meetings. ;-)

I could play along and say I know all about your meetings.. :)

**Comment by levitte** [comment]
@mouse07410, you are right.  I just needed to confirm it to myself, to understand the mechanism that lead to that error.  Basically, it's perfectly possible for an ENGINE to have a different EVP_PKEY_METHOD but use the default low level key method underneath, which is undetectable for the `export_to` functions.

Thanks for your patience.

**Comment by levitte** [comment]
This is no longer WIP

**Comment by mouse07410** [comment]
@levitte thank you fur getting this issue solved.

**Comment by slontis** [comment]
travis test is failing - so this is not quite there yet..

**Comment by petrovr** [comment]
As pointed in #9915 default != openssl method. I expect checks to be based on openssl methods.
Current situation is not expected - see https://github.com/openssl/openssl/issues/9915#issuecomment-595053916 . It is expected sing to fail for all keys and verify to pass. This is not the case.

**Comment by levitte** [comment]
> As pointed in #9915 default != openssl method.

Darnit.  You're right, of course.  Ok, I'll fix.

**Comment by levitte** [comment]
I just modified the check to compare with the actual built-in methods.  @petrovr, does that look more like what you expected?  At the very least, I hope the CIs are happy now.

**Comment by t8m** [comment]
>  At the very least, I hope the CIs are happy now.

Nope :disappointed:

**Comment by levitte** [comment]
Ah!  I had missed one spot...

**Comment by levitte** [comment]
Yay!  CIs are happy!

**Comment by petrovr** [comment]
@levitte ,
Please add "Fixes #9915"

**Comment by levitte** [comment]
> @levitte ,
> Please add "Fixes #9915"

Done.  For now, by adding an empty squash commit.

**Comment by t8m** [comment]
The empty commit does not require re-approval.
